### ISSUE TITLE
Missing a Read Me

### ISSUE THREAD

**Issue by sigmaenigma** [jerryq27/neovim-config#1]
Hello. I would like a readme file please. Thank you

**Comment by jerryq27** [comment]
![image](https://github.com/user-attachments/assets/acf937a9-70e0-4cd7-a8cb-a7767ea4c215)

**Comment by sigmaenigma** [comment]
![94d7n1](https://github.com/user-attachments/assets/54e62ca6-0f43-431c-8d4f-dbf2723cbed3)
